name: seedswild
description: A multivendor ecommerce AI powered SAAS based marketplace
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.3.0'

dependencies: 
  flutter: 
    sdk: flutter
 
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  
  flutter_switch: ^0.3.2
  pin_code_fields: ^8.0.1
  flutter_svg_provider: ^1.0.6
  flutter_rating_bar: ^4.0.1
  dotted_border: 2.1.0
  page_transition: ^2.1.0
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  intl: any
  url_launcher: ^6.2.2
  google_sign_in: ^6.2.1
  another_flushbar: ^1.12.30
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.4.2
  google_fonts: ^6.1.0
dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/animations/
    - assets/images/
  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Quicksand
      fonts: 
        - asset: assets/fonts/QuicksandRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Nunito
      fonts: 
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
